---
name: Python

on: # yamllint disable-line rule:truthy
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          ./requirements.txt
          ./requirements/test.txt
      - name: Test
        run: |
          pytest
      - name: Build package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          pip install build
          python -m build
      - uses: pypa/gh-action-pypi-publish@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*
